name: Ticket Reminder Bot

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable r2u binary repo
        run: |
          sudo bash -c 'echo "deb [signed-by=/usr/share/keyrings/cran-archive-keyring.gpg] \
          https://r2u.rstudio.com/ubuntu jammy/main/" > /etc/apt/sources.list.d/cran-r2u.list'
          curl -fsSL https://r2u.rstudio.com/ubuntu/cran-archive-keyring.gpg | \
            sudo tee /usr/share/keyrings/cran-archive-keyring.gpg > /dev/null

          sudo apt-get update

      - name: Install R (from Ubuntu) and binary R packages
        run: |
          sudo apt-get install -y --no-install-recommends \
            r-base \
            r-cran-dplyr \
            r-cran-lubridate \
            r-cran-httr \
            r-cran-rvest \
            r-cran-stringr

      - name: Run Ticket Reminder
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
        run: |
          Rscript Mett_Bot.R

      - name: Upload reminder status
        uses: actions/upload-artifact@v3
        with:
          name: reminder-status
          path: reminder_status.rds
