name: Ticket Reminder Bot

on:
  schedule:
    - cron: '0 10-16 * * *'
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Enable r2u binary repo
        run: |
          sudo bash -c 'echo "deb [signed-by=/usr/share/keyrings/cran-archive-keyring.gpg] \
          https://r2u.rstudio.com/ubuntu jammy/main/" > /etc/apt/sources.list.d/cran-r2u.list'
          curl -fsSL https://r2u.rstudio.com/ubuntu/cran-archive-keyring.gpg | \
            sudo tee /usr/share/keyrings/cran-archive-keyring.gpg > /dev/null
          sudo apt-get update

      - name: Install R (from Ubuntu) and binary R packages
        run: |
          sudo apt-get install -y --no-install-recommends \
            r-base \
            r-cran-dplyr \
            r-cran-lubridate \
            r-cran-httr \
            r-cran-rvest \
            r-cran-stringr

      - name: Run Ticket Reminder
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          Rscript Mett_Bot.R

      - name: Commit reminder status
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reminder_status.rds
          git diff --cached --quiet || git commit -m "Update reminder status"
          git push
