name: Ticket Reminder Bot

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          
      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr","lubridate","httr","rvest","stringr"))'
        
      - name: Run Ticket Reminder
        env:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
        run: |
          Rscript Mett_Bot.R
